<?foreach ($this->view->getVar('posts') as $post) { ?>
<div>

<h1 class="page-header">
	<a href='/posts/index/<?=$post->id?>'>
		<?=$post->title?>
	</a>
</h1>
	<p>
<?
echo $this->view->getVar('escaper')->escapeHtml($post->getCategoryNameByID()).' '.
$this->view->getVar('escaper')->escapeHtml($post->getUserNameByID()).' '.
$this->view->getVar('escaper')->escapeHtml($post->getPostStatusByID());
?>
	</p>
	<p><?=$post->text?></p>
</div>
<? } ?>

