<ol class="breadcrumb">
<?
foreach ($breadcrumbs as $crumb) {
	if (isset($crumb['controller'])) {
?>
<li><a href="/<?=$this->view->getVar('escaper')->escapeHtml($crumb['controller'])?>/<?=isset($crumb['action']) ? $this->view->getVar('escaper')->escapeHtml($crumb['action']) : ''?>"><?=$this->view->getVar('escaper')->escapeHtml($crumb['name'])?></a></li>
<? } else { ?>
<li class="active"><?=$this->view->getVar('escaper')->escapeHtml($crumb['name'])?></li>
<?
	}
}
?>
</ol>
