<h1 class="page-header">Posts::Add</h1>
<?=\Phalcon\Tag::form(array($this->view->form->getAction())) ?>

	<div class="form-group">
		<label for="<?=$form->get('title')->getName()?>"><?=$form->get('title')->getLabel()?>:</label>
		<?php echo $form->render('title') ?>
		<span class="help-block">
<?php
if (isset($this->view->getVar('errors')[$form->get('title')->getName()])) {
	echo $this->view->getVar('escaper')->escapeHtml($this->view->getVar('errors')[$form->get('title')->getName()]);
}
?>
		</span>
	</div>

	<div class="form-group">
		<label for="<?=$form->get('category_id')->getName()?>"><?=$form->get('category_id')->getLabel()?>:</label>
		<?php echo $form->render('category_id') ?>
		<span class="help-block">
<?php
if (isset($this->view->getVar('errors')[$form->get('category_id')->getName()])) {
	echo $this->view->getVar('escaper')->escapeHtml($this->view->getVar('errors')[$form->get('category_id')->getName()]);
}
?>
		</span>
	</div>

	<div class="form-group">
		<label for="<?=$form->get('text')->getName()?>"><?=$form->get('text')->getLabel()?>:</label>
		<?php echo $form->render('text') ?>
		<span class="help-block">
<?php
if (isset($this->view->getVar('errors')[$form->get('text')->getName()])) {
	echo $this->view->getVar('escaper')->escapeHtml($this->view->getVar('errors')[$form->get('text')->getName()]);
}
?>
		</span>
	</div>

	<div class="form-group">
		<?php echo $form->render('submit') ?>
	</div>

<?=\Phalcon\Tag::endForm ()?>