<?php use Phalcon\Tag as Tag; ?>
<h1 class="page-header">Categories::Edit</h1>
<?=Tag::form(array($this->view->form->getAction())) ?>
	<?php echo $form->render('id') ?>
	<div class="form-group">
		<label for="<?=$form->get('name')->getName()?>"><?=$form->get('name')->getLabel()?>:</label>
		<?php echo $form->render('name') ?>
		<span class="help-block">
<?php
	if (isset($this->view->getVar('errors')[$form->get('name')->getName()])) {
		echo $this->view->getVar('escaper')->escapeHtml($this->view->getVar('errors')[$form->get('name')->getName()]);
	}
?>
		</span>
	</div>

	<div class="form-group">
		<label for="<?=$form->get('description')->getName()?>"><?=$form->get('description')->getLabel()?><?php if ($form->hasMessagesFor('description')) { ?> (<strong style="color:red;"><?php echo $form->getMessagesFor('description')[0]?></strong>)<?php } ?>:</label>
		<?php echo $form->render('description') ?>
	</div>

	<div class="form-group">
		<?php echo $form->render('submit') ?>
	</div>

<?=Tag::endForm ()?>
