<h1 class="page-header">Categories</h1>

<?=\Phalcon\Tag::form(array($this->view->addForm->getAction(),'class' => 'form-inline')) ?>
	<div class="form-group">
		<?php echo $addForm->render('name') ?>
	</div>
	<div class="form-group">
		<?php echo $addForm->render('submit') ?>
	</div>
<?=\Phalcon\Tag::endForm ()?>

<br />

<div class="list-group">
<?foreach ($this->view->getVar('categories') as $category) { ?>
	<div class="list-group-item">
		<h4 class="list-group-item-heading">
			<?=$this->view->getVar('escaper')->escapeHtml($category->name)?>&nbsp;
			<small>
				<?=$this->view->getVar('escaper')->escapeHtml($category->getUserNameByID())?> - 
				<a href='/categories/edit/<?=$category->id?>'>Edit</a> - 
<?if (count((new \Posts)->getPostsByCategoryID($category->id))==0) { ?>
				<a href='/categories/delete/<?=$category->id?>'>Delete</a>
<? } else { ?>
				<span class='delete_forbidden_hint' data-toggle="tooltip" title="" data-original-title="This category contains non-deleted posts">Delete</span>
<? } ?>
			</small>
		</h4>
		<p class="list-group-item-text"><?=$this->view->getVar('escaper')->escapeHtml($category->description)?></p>
	</div>
<? } ?>
</div>

<script>
$('.delete_forbidden_hint').tooltip();
</script>
