<h1 class="page-header">Categories</h1>

<?=\Phalcon\Tag::form(array($this->view->addForm->getAction(),'class' => 'form-inline')) ?>
	<div class="form-group">
		<?php echo $addForm->render('name') ?>
	</div>
	<div class="form-group">
		<?php echo $addForm->render('submit') ?>
	</div>
<?=\Phalcon\Tag::endForm ()?>

<br />

<div class="list-group">
<?foreach ($this->view->getVar('categories') as $category) { ?>
	<div class="list-group-item">
		<h4 class="list-group-item-heading">
			<?=$this->view->getVar('escaper')->escapeHtml($category->name)?>&nbsp;
			<small>
				<?=$this->view->getVar('escaper')->escapeHtml($category->getUserNameByID())?> - 
				<a href='/categories/edit/<?=$category->id?>'>Edit</a> - 
				<a href='/categories/delete/<?=$category->id?>'>Delete</a>
			</small>
		</h4>
		<p class="list-group-item-text"><?=$this->view->getVar('escaper')->escapeHtml($category->description)?></p>
	</div>
<? } ?>
</div>